export const ADD_COUNT = "ADD_COUNT"
export const SUB_COUNT = "SUB_COUNT"
export const ADD_TODO = "ADD_TODO"
export const SET_TODO = "SET_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const STATUS_CHANGE = "STATUS_CHANGE"